query GetCurrentUser @auth(level: USER) {
    appUsers(where: { id: { eq_expr: "auth.uid" } }) {
        id
        email
        profileCompleted
        zipCode
        city
        state
        language
        notificationsEnabled
    }
}

mutation UpsertCurrentUser($email: String!) @auth(level: USER) {
    appUser_upsert(
        data: {
            id_expr: "auth.uid"
            email: $email
        }
    )
}

mutation CompleteOnboarding(
    $email: String!
    $zipCode: String!
    $city: String!
    $state: String!
    $language: String!
    $notificationsEnabled: Boolean!
) @auth(level: USER) {
    appUser_upsert(
        data: {
            id_expr: "auth.uid"
            email: $email
            profileCompleted: true
            zipCode: $zipCode
            city: $city
            state: $state
            language: $language
            notificationsEnabled: $notificationsEnabled
        }
    )
}