// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxwsRLFRA60Lkdii_jAgDxaqoUY84ysY',
    appId: '1:391033599983:web:b6c5eddb3e9d6adf53281a',
    messagingSenderId: '391033599983',
    projectId: 'we-the-people-f1776',
    authDomain: 'we-the-people-f1776.firebaseapp.com',
    storageBucket: 'we-the-people-f1776.firebasestorage.app',
    measurementId: 'G-E8GRWNGS45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBECmlre4JC3ko-fAqIc5y2P-tD6N--5Qo',
    appId: '1:391033599983:android:9ae704cb426e48e353281a',
    messagingSenderId: '391033599983',
    projectId: 'we-the-people-f1776',
    storageBucket: 'we-the-people-f1776.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Ie5zz53_mG5NmgTXGzNmXtgGpPswD18',
    appId: '1:391033599983:ios:aa64dc6a4f51dae953281a',
    messagingSenderId: '391033599983',
    projectId: 'we-the-people-f1776',
    storageBucket: 'we-the-people-f1776.firebasestorage.app',
    iosBundleId: 'com.example.weThePeople',
  );
}